### ISSUE TITLE
BUG: uploadFiles not working

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble-react#1011]
**Describe the bug**
getting Uncaught (in promise) ReferenceError: colors is not defined
if I remove the uploadFiles action, rest works fine

![Image](https://github.com/user-attachments/assets/f3749c26-6344-41b8-8f78-4f9b9ce3d350)

```yaml
- Button:
      label: Upload File
      loading: ${!!ensemble.storage.get(COMMON.uploadPackingSlipLoading)}
      styles:
        visible: ${!packingSlip}
      onTap:
        pickFiles:
          allowedExtensions:
            - pdf
            - docx
            - jpg
            - png
          onComplete:
            executeCode:
              body: |
                ensemble.storage.set(COMMON.uploadPackingSlipLoading, true);
              onComplete:
                invokeAPI:
                  name: createMediaByName
                  inputs:
                    tenantId: ${getCurrentTenant()}
                    token: ${ensemble.user.accessToken}
                    uploadInfo:
                      name: '${files[0].name}'
                    tags: 'PATIENT_CONSENT'
                    patientId: ${currentPatient.match.patient.id}
                onResponse:
                  uploadFiles:
                    files: ${files}
                    uploadApi: uploadFile
                    inputs:
                      tenantId: ${getCurrentTenant()}
                      token: ${ensemble.user.accessToken}
                    onComplete:
                      invokeAPI:
                        name: createPatientDocument
                        inputs:
                          tenantId: ${getCurrentTenant()}
                          token: ${ensemble.user.accessToken}
                          docsInfo:
                            patientId: ${currentPatient.match.patient.id}
                            documentType: CONSENT
                            mediaId: ${createMediaByName.body.data.createMediaPutURL.id}
                        onResponse:
                          invokeAPI:
                            name: setTaskDocuments
                            inputs:
                              tenantId: ${getCurrentTenant()}
                              token: ${ensemble.user.accessToken}
                              patientDocumentIds: ${[createPatientDocument.body.data.createPatientDocument.id]}
                              taskId: ${ensemble.storage.get('stepper').steps[workflowStepper.activeStep].id}
                            onResponse:
                              executeCode:
                                body: |
                                  const stepper = ensemble.storage.get('stepper')
                                  const patientDoc = createPatientDocument.body.data.createPatientDocument
                                  stepper.steps[workflowStepper.activeStep].taskDocuments = [{
                                    createdAt: patientDoc.createdAt,
                                    patientDocument: patientDoc
                                  }]
                                  ensemble.storage.set('stepper', {...stepper});

                                  ensemble.storage.set(COMMON.drugTrackDocuments, [{ patientDocument: patientDoc }]);

                                  const patientsDocuments = ensemble.storage.get(COMMON.patientsDocuments);
                                  if (patientsDocuments) {
                                    patientsDocuments.push(patientDoc);
                                    ensemble.storage.set(COMMON.patientsDocuments, [...patientsDocuments]);
                                  }

                                  ensemble.storage.set(COMMON.uploadPackingSlipLoading, false);
```
