### ISSUE TITLE
Expressions with ensemble.storage are not re-evaluated when storage changes

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#105]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by evshi** [comment]
@sibteali786 I think you raised this when developing Embrace app. After testing this on mobile side I think this is working as designed. See this YAML and paste into studio to test

```yaml
View:
  onLoad:
    executeCode:
      body: |-
        ensemble.storage.set('value', 1)
  # Optional - style the screen
  styles:
    scrollableView: true

  # Optional - set the header for the screen
  header:
    title: Home

  # Specify the body of the screen
  body:
    Column:
      styles:
        padding: 24
        gap: 8
      children:
        - Text:
            text: ${ensemble.storage.get('value')}
        - Button:
            label: Update value
            onTap:
              executeCode:
                body: |-
                  ensemble.storage.set('value', 2)
```

Clicking the button does not update the text value. I believe the recommended approach here is to use the `setText` method or other appropriate setter for the widget you'd like to update.
