### ISSUE TITLE
Share styling easily across components

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#122]
**Is your feature request related to a problem? Please describe.**
Styling widgets is very verbose, often requiring multiple lines of YAML.

**Describe the solution you'd like**
A concise format to style my widgets and minimize the overall lines of YAML required.

**Describe alternatives you've considered**

**Additional context**

**Comment by evshi** [comment]
**Proposal**

- Provide a built-in set of CSS style names, i.e. tailwind
- Configure design tokens and customize style names in a theme file
- Add style names to widgets in a dedicated `names` prop that takes an interpolated string
- Can still override names with CSS properties in line as usual
- Combine with custom widgets feature to really make screens concise

**Example**

`theme.yaml`
```yaml
Tokens:
  Colors:
     [colorName]: # value in rgba/hex
  Spacing:
     [spacingName]: # value in px/rem
  Animation:
     [animationName]: # define custom animations
Styles:
   [name]:
      # CSS Properties populated by tokens

```

`screen.yaml`
```yaml
[Widget]:
  styles:
    names: "${name} builtIn"
    # CSS Properties
```
