### ISSUE TITLE
ScreenContext is stale when nested actions are used

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#129]
**Describe the bug**
When two actions are used in nested fashion, the second action is unable to access properties exposed by first action

**To Reproduce**

```yaml
# Not working (potential cause: id of pickFiles hasn't yet registered when uploadFiles is using it)
Column:
  children:
    - Button:
        label: Upload Files
        onTap:
          pickFiles:
            id: myFiles
            allowMultiple: true
            allowedExtensions:
              - jpg
              - png
              - mov
            onComplete:
              uploadFiles:
                id: myUploader
                files: ${myFiles.files}
                uploadApi: uploadFile
                onComplete:
                  executeCode: console.log(myUploader.body)
                onError:
                  executeCode: console.log('Upload error')
```

**Expected behavior**
To be able to use `myFiles.files` in `uploadFiles` action, and similarly, `myUploader.body` in `onComplete` action
