### ISSUE TITLE
Inputs passed to screens are not recognized in the context 

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble-react#222]
**Describe the bug**
When we pass an input to another screen, it's not recognized in the context of another screen.

**To Reproduce**
this is a sample code I am using under an item-template 
```yaml
- Button:
      label: View full record
      styles:
        borderRadius: 6
      onTap:
        navigateScreen:
          name: Select DOS
          inputs:
            data: ${patient}
```
when I move to select DOS screen in console I see an error 
<img width="446" alt="Screenshot 2023-12-06 at 11 35 13 AM" src="https://github.com/EnsembleUI/ensemble-react/assets/62849614/bdb1eb49-bf1f-46c4-8535-b53be4777e77">
- data is not defined.
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
