### ISSUE TITLE
Nested item-templates are not being evaluated properly

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble-react#228]
**Describe the bug**
I am trying to provide a value to item-template's `data` attribute and its not been evaluated unless its either an API name or its from ensemble local storage.

**To Reproduce**

1. Make an Itemtemplate for any widget like Row, Column etc 
2. in data attribute instead of API name or local storage get method, use a variable which if evaluated results in a value.
```yaml
- DataGrid:
    DataColumns:
      - label: User
      - label: Last Active
    item-template:
      data: getData.body.records
      name: user
      template:
        DataRow:
          children:
            # Person
            - Row:
                crossAxis: center
                gap: 15
                children:
                  - Avatar:
                      alt: sana
                      name: ${user.fields.name}
                      styles:
                        backgroundColor: "#F4F4F4"
                        color: grey
                  - Column:
                      item-template:
                        data: user.fields.groups
                        name: usr
                        template:
                          Text:
                            text: ${usr}
                            styles:
                              fontSize: 20
                  - Column:
                      crossAxis: start
                      children:
                        - Text:
                            text: ${user.fields.name}
                        - Text:
                            text: ${user.fields.email}
                            styles:
                              fontWeight: normal
                              fontSize: 12px
                              color: "#767676"
                                                          
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
