### ISSUE TITLE
Widget inputs not recognized by the invokeApi context ?

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble-react#265]
**Describe the bug**
When i try to send an input to InvokeApi in a screen using a screen input from another screen, this input is not recognized the the context of the invokeApi.

**To Reproduce**
1. Pass an input to a modal like 
```yaml
onTap:
  navigateModalScreen:
    name: Dashboard Modal
    styles:
      position: top
      padding: 20
      width: '70%'
    inputs:
      patients: ${ensemble.storage.get("patients")}
```
2. Then go to this widget and invokeAPI using this input as value to invokeAPI input 
```yaml
onLoad:
    invokeApi:
      name: postPatients
      inputs:
        mrn: ${patients}
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
