### ISSUE TITLE
The item-template name should be accessible in navigateScreen inputs

### ISSUE THREAD

**Issue by sibteali786** [EnsembleUI/ensemble-react#305]
**Describe the bug**
For now we are not able to access item-template name ( data key ) in sub-sequent events like onResponse, onTap etc in case for DataGrid 

This is for DataGrid specifically.
**To Reproduce**
- Take a DataGrid and on DataRow call an onTap event
- now we can simply use execute code and it will work fine and show item-template name data
-  Now try to use navigateScreen and this item-template name property wont be accessible in its inputs.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sibteali786** [comment]
updates to this issue i was trying to access `data` property from DataRow's onTap in subsequent events and was not able to access it.
- This works fine for executeCode block and scriptName as well if they are directly under onTap otherwise this version 
```yaml
item-template:
              data: ensemble.storage.get("patients")
              name: incompleteTask
              template:
                DataRow:
                  onTap:
                    invokeApi:
                      name: getPatientByMrn
                      inputs:
                        mrn: ${data.incompleteTask.patientId[0].patientMrn}
                      onResponse:
                        executeCode:
                          scriptName: rowClickHandler.js
                          onComplete: 
                            navigateScreen:
                              name: PostEnrollment
                              inputs:
                                patient: ${ensemble.storage.get('currentPatient')}
                                options: ${ensemble.storage.get("options")}
                                program: ${ensemble.storage.get('program')}
                                isPostEnroll: true
```
does not work 
in rowClickHandler.js 
console.log('Patients', data);
i get undefined for this
