### ISSUE TITLE
Support footer of any size

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#339]
Currently the footer component is assumed to be 56 px tall and the rest of the page is sized accordingly. This is an artificial restriction. Technically the footer can be of any height and the page can just "fold underneath" it. In other words, the footer is stacked on top of the page and the page is free to scroll under it

**Comment by anserwaseem** [comment]
@evshi @sagardspeed2  `56px` is the default footer height I got from our flutter framework impl, we can override height of the footer e.g.

```yaml
footer:
    styles:
      backgroundColor: ${colors.primary['100']}
      height: 80px
    children:
      - Text:
          text: © 2021 Ensemble
          styles:
            color: blue
            fontSize: 20px
            fontWeight: 500
            alignSelf: center
```
