### ISSUE TITLE
Support dynamic DataGrid columns

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#371]
**Is your feature request related to a problem? Please describe.**
DataGrid columns take a static list but sometimes we want to use the same DataGrid view for different datasets with variable columns.

**Describe the solution you'd like**

- Add binding support for data column to be variable list
- Support key value on DataColumn
- Add item-template support for DataRow. The template should be applied over each column in the row.

**Describe alternatives you've considered**

**Additional context**

**Comment by evshi** [comment]
@sagardspeed2 consider this YAML
```js
const mydata = [ { key1: "value", key2: 2}, {key1: "foo", key2: 3"]
```

```yaml
DataGrid:
  DataColumns:  ${Object.keys(head(myData))}
  item-template:
    data: ${myData}
    name: data
    template:
       DataRow:
          item-template: ${Object.values(data)}
          data: value
          template:
              Conditional:
                  conditions:
                      - if: ${isString(value}
                         Text:
                             ....

```
