### ISSUE TITLE
DataRow's onTap action is fired when it's children's onTap should be

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#396]
**Describe the bug**
In Datagrid widget, I have an onTap on DataRow and a Collapsible, among other widgets as its children. When I click on Collapsible widget, so both actions gets fired i.e., Collapsible's and DataRow's.

**To Reproduce**
Use this example yaml to reproduce the issue:

```yaml
- DataGrid:
      DataColumns:
        - label: Number
        - label: Name
      item-template:
        data: [1, 2]
        name: dummyData
        template:
          DataRow:
            onTap:
              navigateScreen:
                name: forms
            children:
              - Text:
                  text: ${dummyData}
              - Collapsible:
                  expandIconPosition: "end"
                  items:
                    - key: "2"
                      label: Here is my label 2
                      children:
                        Text:
                          text: Here is my value 2
                  onCollapse:
                    executeCode: |
                      console.log('HelloC', data)
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
