### ISSUE TITLE
Height property is not respected on body Column widget

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#464]
```yaml
body:
  Column:
     styles:
        height: 100vh
```

should take up entire screen
