### ISSUE TITLE
onResponse of the apis under API block are not working

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#465]
**Describe the bug**
`onResponse` of the apis under API block of the screen are not working.

**To Reproduce**
Checkout this yaml
```yaml
View:
  onLoad:
    executeCode: |
      ensemble.invokeAPI('getDummyProducts');
  body:
    Text:
      text: This is a test

API:
  getDummyProducts:
    method: GET
    uri: https://dummyjson.com/products
    onResponse:
      executeCode: |
        console.log('response');
```

**Expected behavior**
`onResponse` working
