### ISSUE TITLE
TextInput.value doesnt return latest value

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#497]
**Describe the bug**
onTap of button, we are not getting latest value of TextInput.

**To Reproduce**
Use this yaml as an example: (try replacing content of customWidgets.yaml in kitchen-sink project to check)

```yaml
View:
  header:
    title:
      Header:

  onLoad:
    executeCode: |
      ensemble.storage.set('defaultInputValue', 'default value');

  body:
    Column:
      children:
        - TextInput:
            id: myTextInput
            label: Text Input
            value: ${ensemble.storage.get('defaultInputValue')}
        - Button:
            label: Submit Input
            onTap:
              executeCode:
                body: |
                  const val = myTextInput.value
                  console.log(val);
```
