### ISSUE TITLE
InvokeAPI Response Not Passed to NavigateExternalScreen Action

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#512]
**Describe the bug**
This YAML should work but it doesn't

```yaml
invokeAPI:
  name: myApi
  onResponse:
     navigateExternalScreen:
        url: ${response.data.someUrl}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi here passed argumets are evaluated correctly, but the problem is related that passing the api response in next action that is `navigateExternalScreen` is not working. I mean the response from `invokeApi` are not being passed in `navigateExternalScreen`.

Otherwise
```yaml
invokeAPI:
                name: getDummyProducts
                onResponse:
                  navigateExternalScreen:
                    url: ${ensemble.storage.get('targetScreen')}
```

this YAML is working fine and arguments are evaluating correctly
