### ISSUE TITLE
Can't pass objects into ensemble.invokeAPI

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#514]
**Describe the bug**
Issue is the JSON.stringify

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi as per this example, I am able to pass object as reqbody in `ensemble.invokeAPI`

```YAML
View:
  onLoad:
    executeCode: |
      ensemble.storage.set('product', {title: 'Hello'})
      
body:
  Column:
    styles:
      names: page
      gap: 8px
    children:
      - Card:
          styles:
            maxWidth: unset
            width: unset
          children:
            - Text:
                styles:
                  names: heading-3
                text: Add product with object in api
            - Button:
                label: Add product
                onTap:
                  executeCode: |
                    ensemble.invokeAPI('addProduct', {product:ensemble.storage.get('product')}).then((res) => {
                      console.log(res)
                    })

API:
  addProduct:
    method: POST
    uri: https://dummyjson.com/products/add
    inputs:
      - product
    body:
      product: ${product}
    onResponse:
      executeCode: |
        console.log(response.body);
  ```
  
  In network inspector
  
<img width="912" alt="image" src="https://github.com/EnsembleUI/ensemble-react/assets/31651612/3233cc35-6082-4fd7-ab31-85a39ab14c68">
