### ISSUE TITLE
Search results aren't being refreshed properly

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#565]
**Describe the bug**
Go to https://map-dev.apps.okd.cell-0001.atlas-cloud.health/programs/reports
Login with creds (ask @sibteali786 or @anserwaseem )
Click `Program matched Reasons` from dropdown
Search for "leu"
Search for "patient"
Notice how the first results are not removed

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi as I mentioned ago that this is not related anything wrong in select widget, the props provided in EDL has some issue, When we search options on this atlas page, there are records with same `programName` and EDL is using the `programName` as value, when I changes value field as `id` of the record, it is working fine.


https://github.com/EnsembleUI/ensemble-react/assets/31651612/f8300bdc-0a99-488d-aa96-d711c8449a45

Current EDL on atlas programs report page
```YAML
Search:
      id: 'searchProgramInput'
      styles:
        width: 320px
        borderRadius: ${spacing['2']}
        borderWidth: 2
        borderStyle: solid
        borderColor: ${colors.gray['200']}
        backgroundColor: ${colors.gray['50']}
      placeholder: ${placeholder}
      item-template:
        data: ensemble.storage.get("found-programs")
        name: foundProgram
        template:
          Text:
            text: ${foundProgram.programName}

      searchKey: programName
      onSearch:
        debounceMs: 400
        invokeApi:
          name: searchPrograms
          inputs:
            value: ${search}
            token: ${ensemble.user.accessToken}
          onResponse:
            executeCode:
              scriptName: setFoundProgramsData.js
      onSelect:
        executeCode:
          body: |
            ensemble.storage.set('selectedProgramId', value.id);
          onComplete:
            invokeAPI:
              name: getProgramMatchReasonsData
              inputs:
                programId: ${ensemble.storage.get("selectedProgramId")}
                token: ${ensemble.user.accessToken}
              onResponse:
                executeCode:
                  scriptName: setProgramMatchReasonsData.js
```

and EDL that I modified

```YAML
Search:
      id: 'searchProgramInput'
      styles:
        width: 320px
        borderRadius: ${spacing['2']}
        borderWidth: 2
        borderStyle: solid
        borderColor: ${colors.gray['200']}
        backgroundColor: ${colors.gray['50']}
      placeholder: ${placeholder}
      item-template:
        data: ensemble.storage.get("found-programs")
        name: foundProgram
        template:
          Text:
            text: ${foundProgram.programName}

      searchKey: id
      onSearch:
        debounceMs: 400
        invokeApi:
          name: searchPrograms
          inputs:
            value: ${search}
            token: ${ensemble.user.accessToken}
          onResponse:
            executeCode:
              scriptName: setFoundProgramsData.js
      onSelect:
        executeCode:
          body: |
            ensemble.storage.set('selectedProgramId', value.id);
          onComplete:
            invokeAPI:
              name: getProgramMatchReasonsData
              inputs:
                programId: ${ensemble.storage.get("selectedProgramId")}
                token: ${ensemble.user.accessToken}
              onResponse:
                executeCode:
                  scriptName: setProgramMatchReasonsData.js
```

see the `searchKey` prop, in short, the value of all options inside autocomplete must be unique.
