### ISSUE TITLE
Properties of Ensemble.user are undefined when used directly under onLoad of a screen

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#615]
**Describe the bug**

**To Reproduce**
```yaml
View:
  onLoad:
    executeCode: console.log(ensemble.user.accessToken)
```

**Expected behavior**
ensemble.user.accessToken to return a value

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
