### ISSUE TITLE
Support widget setters for flutter compatibility

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#619]
**Is your feature request related to a problem? Please describe.**
Support setters of widgets like we do in flutter side.

### Example:
```yaml
View:
  body:
    Column:
      children:
        - Text:
            id: myText
            text: Initial Text
        - Button:
            label: Set text
            onTap:
              executeCode: myText.text = 'i am set'
```

**Describe the solution you'd like**
Support react way `myText.setText('new Text')` for backward compatibility and `myText.text = 'new Text'` for flutter compatibility

**Describe alternatives you've considered**

**Additional context**
