### ISSUE TITLE
onSelect of Search widget is not working for local data

### ISSUE THREAD

**Issue by justEhmadSaeed** [EnsembleUI/ensemble-react#624]
**Describe the bug**
When I click on an item of the `Search` widget, the onSelect doesn't work and the default selection of the item also doesn't work.
This happens when I use the local array for data instead of an API. screen recording and yaml is attached below.

**To Reproduce**

https://github.com/EnsembleUI/ensemble-react/assets/46846821/7a22c643-66fe-423b-a9e2-803454125380

YAML:
```yaml
Widget:
  inputs:
    - label
    - widgetId
    - placeholder
  body:
    Column:
      styles:
        gap: ${spacing['2']}
      children:
        - Text:
            text: ${label}
            styles:
              fontWeight: ${typography.fontWeight.semibold}
        - Search:
            id: ${widgetId}
            required: true
            styles:
              width: 100%
              borderRadius: ${spacing['2']}
              borderWidth: 2
              borderStyle: solid
              borderColor: ${colors.gray['200']}
              backgroundColor: ${colors.gray['50']}
            placeholder: ${placeholder}
            item-template:
              data: ${ensemble.storage.get('filteredFinancialClasses') ?? FinancialClasses}
              name: financialClass
              template:
                Column:
                  children:
                    - Text:
                        styles:
                          fontWeight: ${typography.fontWeight.semibold}
                        text: ${financialClass}
            searchKey: financialClass
            onSearch:
              debounceMs: 400
              executeCode: |
                const filteredClasses = FinancialClasses.filter((financialClass) => financialClass.toLowerCase().includes(search.toLowerCase()));
                ensemble.storage.set('filteredFinancialClasses', filteredClasses);
            onSelect:
              executeCode: |
                console.log(value);
                ensemble.storage.set(widgetId, value);

```

Array:
```javascript
const FinancialClasses = [
    "CHAMPVA",
    "CHARITY",
    "COMMERCIAL",
    "CO_PAY",
    "DEVICE_CO_PAY",
    "EMPLOYEE",
    "GOVT_OTHER",
    "LIABILITY",
    "LIFE_INSURANCE",
    "MEDICAID",
    "MEDICARE",
    "MEDICARE_ADVANTAGE",
    "MEDICARE_PART_A",
    "MEDICARE_PART_D",
    "MEDICARE_REPLACEMENT",
    "SELF_PAY",
    "SUPPLEMENT",
    "TRAVEL",
    "TRICARE",
    "VA",
    "WORKERS_COMP",
    "OTHER",
  ]
```
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
