### ISSUE TITLE
DataGrid renders empty space for Conditional widget when its result is null

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#708]
**Describe the bug**
When a Conditional widget is used in Datagrid, and when Conditonal widget's result is null (i.e. no conditions is satisfied to render a widget), it still takes a place in Datagrid

**To Reproduce**
Use this yaml:

```yaml
DataGrid:
  DataColumns: "${1>1 ? [{label:'PATIENT'}, {label:'ADVOCATE'}, {label: 'ID'}, {label: 'MANAGER'}] : [{label:'PATIENT'}, {label: 'ID'}, {label: 'MANAGER'}]}"
  item-template:
    data:
      [
        {
          id: "1",
          patient: "John",
          advocate: "Mike Ross",
          manager: "Charles",
        },
        {
          id: "2",
          patient: "Reuben",
          advocate: "Harvey Dent",
          manager: "Jimmy",
        },
      ]
    name: dummyData
    template:
      DataRow:
        children:
          - Text:
              text: ${dummyData.patient}
          - Conditional:
              conditions:
                - if: ${1>1}
                  Text:
                    text: ${dummyData.advocate}
          - Text:
              text: ${dummyData.id}
          - Text:
              text: ${dummyData.manager}
```
![image](https://github.com/user-attachments/assets/78b9973e-71a0-44a2-98c8-1b23e71c8a72)

try commenting out whole Conditional widget and it'd start working correctly.
