### ISSUE TITLE
Sub-Items in the Menu

### ISSUE THREAD

**Issue by justEhmadSaeed** [EnsembleUI/ensemble-react#799]
**Is your feature request related to a problem? Please describe.**
Need sub items for the menu items that can be collapsed or expanded.
Feature Request [Ticket](https://atlashealth.atlassian.net/browse/MORPHEUS-151)
![image](https://github.com/user-attachments/assets/0d63794e-de3e-452a-a53e-7ca9f1e244a9)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by amin-nas** [comment]
@anserwaseem @evshi here's a proposal for EDL

```yaml
  Sidebar:
    styles:

      # expose styling of group and its items
      groupPadding:
      groupItemTextStyle:

    items:
      - type: navItem # default type, and what is supported today
        label: Home 
        page: home
        
      - type: navGroup
        label: Products
        collapsable: true # default
        collapseByDefault: 
        collapseIcon:
          # icon properties
        expandIcon:
          # icon properties  
        items:
          - label: Product A
            page: products/a
          - label: Product B
            page: products/b
```

**Comment by anserwaseem** [comment]
@amin-nas 
In addition to `label`, we also support `customItem`.
If there are child items (e..g Product A, Product B in EDL above) - a sub-menu can be displayed, so what purpose does `type` serve?

**Comment by amin-nas** [comment]
> @amin-nas In addition to `label`, we also support [customItem](https://docs.ensembleui.com/screens-and-widgets/screen-structure#bottomnavbaritemscustomitem). If there are child items (e..g Product A, Product B in EDL above) - a sub-menu can be displayed, so what purpose does `type` serve?

My thinking is that

1. Better to be explicit, instead of saying "if you add sub-items, then it behaves like a group"
2. We can expand on this and support more types, such as divider, nav section header, ...

cc @vusters, @kmahmood74 - please chime in if you have other ideas

**Comment by evshi** [comment]
@anserwaseem @amin-nas @justEhmadSaeed this layout is possible already via custom widgets and collapsible containers, and actions.

If we're trying to optimize the YAML, then adding additional attributes to support this seems counterproductive. I think we need to maintain the decoupling of routing and presentation and not create a specialized way to define sub menus. Is there a strong reason not to support nested ViewGroups? A ViewGroup represents a logical group of routes in your app, and supports defining presentation for each. If an item routes to another ViewGroup, then that is a sub menu?

**Comment by vusters** [comment]
> @anserwaseem @amin-nas @justEhmadSaeed this layout is possible already via custom widgets and collapsible containers, and actions.
> 
> If we're trying to optimize the YAML, then adding additional attributes to support this seems counterproductive. I think we need to maintain the decoupling of routing and presentation and not create a specialized way to define sub menus. Is there a strong reason not to support nested ViewGroups? A ViewGroup represents a logical group of routes in your app, and supports defining presentation for each. If an item routes to another ViewGroup, then that is a sub menu?

It'll be pretty miserable UX for the user though. I think we should simply ViewGroup rather than making it link to different ViewGroups.. e.g. which is the main one? what happened when i delete one ?, not to mention it'll be hard to support in the Visual Editor. I think we should stick to a simple flow. What @amin-nas has above is simple enough:
```
...
Sidebar:
  items:
    - label: Home
       page: Home
    - label: Settings
       page: # this is now optional if you want the root to be navigable or not
       type: navGroup
       groupOptions:
           icon*...
        items:
             ....
```

The important thing is `page` attribute has to be optional for the group, the type will help you differentiate that and be more explicit.
