### ISSUE TITLE
Form items should update their value when binding value changes and is different from current value

### ISSUE THREAD

**Issue by evshi** [EnsembleUI/ensemble-react#844]
**Describe the bug**
Checkbox does not update the value properly if the binding changes. See Date widget and tests for example behavior. Duplicate tests for Checkbox, Dropdown, TextInput, etc.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sagardspeed2** [comment]
@evshi here is my YAML

```yaml
View:
  onLoad:
    executeCode:
      body: |
        ensemble.storage.set('checkbox', false)
        
  body:
    Column:
      styles:
        names: page
      children:
          - Button:
            label: Go Back
            onTap:
              executeCode: |
                ensemble.storage.set('checkbox', !ensemble.storage.get('checkbox'))
          - Card:
            styles:
              maxWidth: unset
              width: unset
            children:
              - Form:
                  id: myForm
                  children:
                     - Row:
                        item-template:
                          data: [0, 1, 2]
                          name: cd
                          template:
                            Checkbox:
                              id: ${'cb' + cd}
                              trailingText: ${'Check me' + cd}
                              value: ${ensemble.storage.get('checkbox')}
                              onChange:
                                executeCode: |-
                                  console.log('isChecked', value);
```

https://github.com/user-attachments/assets/93a436c4-cd6d-453d-8b99-5f95cc3b7dd1

when I am changing by binding through button, checkboxes values are updating
