### ISSUE TITLE
inputType: 'number' in the TextField not accepting decimals

### ISSUE THREAD

**Issue by justEhmadSaeed** [EnsembleUI/ensemble-react#868]
**Describe the bug**
There should be a mechanism to allow the decimals with inputType: 'number' of TextInput

```
      TextInput:
                 id: updateAmount
                  label: Award Amount
                  hintText: Enter an amount
                  inputType: 'number'
                  required: true
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
