### ISSUE TITLE
No Context in item-template of Collapsible widget

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#885]
**Describe the bug**
Use `item-template` in Collapsible widget. Example YAML
```yaml
Collapsible:
  item-template:
    data: [1, 2, 3]
    name: p
    template:
      CollapsibleItem:
        key: ${p}
        label: ${'hello' + getDateLabel(p)}
        children:
          Text:
            text: ${'world' + p + ensemble.storage.get("iconName")}
```

**Errors**
![image](https://github.com/user-attachments/assets/0143dc23-a037-41c1-9cfa-b0e4a67aae77)
![image](https://github.com/user-attachments/assets/b2b99d47-36e0-4516-a39c-c5dea97cf16c)
fyi: getDateLabel is available in common.js script in kitchen-sink app
