### ISSUE TITLE
Enhance Search widget

### ISSUE THREAD

**Issue by anserwaseem** [EnsembleUI/ensemble-react#96]
## AC:
- add `onValueChange` property that handles the search via action (invokeAPI) 

### Proposed YAML:
```yaml
Search:
  onValueChange: getEmails
```

or

```yaml
Search:
  onValueChange: 
    invokeAPI: getData
      inputs:
        limit: 100
```

### Additional context:
Extending the original [ticket](https://github.com/EnsembleUI/ensemble-react/issues/23) for Search widget
