### ISSUE TITLE
Context issue in APIs

### ISSUE THREAD

**Issue by sharjeelyunus** [EnsembleUI/ensemble-react#985]
**Describe the bug**
I have 2 `uploadFile` api defs

1 in the screen of patient app
```yaml
uploadFile:
    uri: '${response.body.url}'
    headers:
      Content-Type: application/octet-stream
    method: PUT
```

2nd in a separate widget of a separate app (common app)
```yaml
uploadFile:
    uri: '${response.body.data.createMediaPutURL.url}'
    headers:
      Content-Type: application/octet-stream
      x-atlas-tenant: ${tenantId}
    method: PUT
```

instead of calling the api defined in the screen, its trying to call the api from the separate app's widget🤯 which is breaking the patient app

**Additional context**
https://atlashealth.atlassian.net/browse/NEO-1765
